server:
  port: 3001

db: 
  type: 'postgres'  
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'live_db'
  migration: true
  synchronize: false


graphql:
  playground: false

